/**
 * Maps tensorpc IconType enum values to MUI icon component names.
 * Mirrors tensorpc.dock.core.uitypes.IconType
 */
export const ICON_TYPE_MAP: Record<number, string> = {
  0: "RestartAlt",
  1: "Menu",
  2: "Settings",
  3: "Save",
  4: "Close",
  5: "ExpandMore",
  6: "ExpandLess",
  7: "Add",
  8: "ChevronLeft",
  9: "ChevronRight",
  10: "Delete",
  11: "AddCard",
  12: "Clear",
  13: "Fullscreen",
  14: "PlayArrow",
  15: "Pause",
  16: "Stop",
  17: "MoreVert",
  18: "FullscreenExit",
  19: "Code",
  20: "Terminal",
  21: "Videocam",
  22: "CameraAlt",
  23: "DragHandle",
  24: "Dataset",
  25: "DataObject",
  26: "DataArray",
  27: "Cached",
  28: "SwapVert",
  29: "Refresh",
  30: "Grid3x3",
  31: "Help",
  32: "Visibility",
  33: "Mic",
  34: "PlayCircleOutline",
  35: "DragIndicator",
  36: "Cancel",
  37: "Done",
  38: "Preview",
  39: "Build",
  40: "VisibilityOff",
  41: "ManageAccounts",
  42: "AccountCircle",
  43: "BugReport",
  44: "Dashboard",
  45: "DashboardCustomize",
  46: "Check",
  47: "ContentCopy",
  48: "ContentPaste",
  49: "ContentCut",
  50: "TableView",
  51: "Image",
  52: "Merge",
  53: "DoubleArrow",
  54: "AccountTree",
  55: "Timeline",
  56: "FiberManualRecord",
  57: "NavigateNext",
  58: "NavigateBefore",
  59: "SkipNext",
  60: "SkipPrevious",
  61: "RadioButtonChecked",
  62: "StopCircleOutlined",
  63: "Block",
  64: "Download",
  65: "Upload",
  66: "Link",
  67: "LinkOff",
  68: "Search",
  69: "Info",
  70: "QueryStats",
  71: "BarChart",
  72: "Adb",
  73: "CloudDownload",
  74: "CloudUpload",
  75: "Insights",
  76: "KeyboardDoubleArrowRight",
  77: "KeyboardDoubleArrowLeft",
  78: "KeyboardArrowRight",
  79: "KeyboardArrowLeft",
  80: "KeyboardArrowDown",
  81: "KeyboardArrowUp",
  82: "KeyboardDoubleArrowDown",
  83: "KeyboardDoubleArrowUp",
  84: "Shortcut",
  85: "Input",
  86: "Output",
  200: "Reactflow",
  201: "Markdown",
};

export function getIconName(iconValue: unknown): string | null {
  if (typeof iconValue === "number" && iconValue in ICON_TYPE_MAP) {
    return ICON_TYPE_MAP[iconValue];
  }
  if (typeof iconValue === "string") {
    return iconValue;
  }
  return null;
}
